config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about'

  get 'pages/contact'
  get '/listings' => "listings#index"
  get 'seller' => "listings#seller"
  get '/search' => 'pages#search'

  root 'pages#home'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  resources :listings do 
      resources :orders, only: [:new, :create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
                                    :storage => :dropbox,
                                    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
                        
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image

  belongs_to :user
  belongs_to :category

  searchkick
end

app/models/order.rb
class Order < ActiveRecord::Base
	 validates :address, :city, :state, presence: true

	 belongs_to :listing
     belongs_to :buyer, class_name: "User"
     belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only:[:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC").page(params[:page])

  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def search 
  end
  # GET /listings/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.category_id = params[:category_id]
    @listing.user_id = current_user.id

    current_user.save
    

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing.category_id = params[:category_id]
    @listing.user_id = current_user.id


    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image, :category_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json


  # GET /orders/1


  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end


  # POST /orders
  # POST /orders.json

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @order.buyer_id = current_user.id
    @seller = @listing.user
    @order.listing_id = @listing.id
    @order.seller_id = @seller.id

        begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      :currency => "usd",
      :recipient => @seller.recipient
      )


    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  	 	@listings = Listing.all.limit(4)
  end

  def contact
  end

  def search
  	if params[:search].present?
  		@listings = Listing.search params[:search], page: params[:page], per_page: 4
  	else
  		@listings = Listing.all
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

      <%= link_to "EtsyClone", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Sell on Etsy", new_listing_path %> </li>    
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="container">

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-12">
    <div class="search-fm">
      <%= form_tag search_path, class: "navbar-form ", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "What are you shopping for?", class: "form-control text-center", id: "form-search", style: "width: 350px; height: 50px; margin: 0px 0px 5px;
"  %>
             <%= submit_tag "Search", class: "btn button-search", style: 
             " width: 150px; margin: 0 10px 5px 11px; height: 50px;" %>
          </div>
      <% end %> 
    </div>
  </div>  
</div>
         <div class="row">
           <% @listings.each do |listing| %>
               <div class="col-md-3">
                 <div class="panel panel-default">
                   <div class="panel-heading preview">
                   <%= link_to listing do %> 
                   <%= image_tag listing.image.url(:medium) %>
                   <% end %>
                   </div>
                   <div class="panel-body">
                     <h3 id="listing-name"><%= listing.name %></h3>
                  <span id="list-price"><%= link_to number_to_currency(listing.price), listing %></span>
                   
                
                     <% if (user_signed_in?) && (current_user == listing.user) %>                    
                        <%= link_to 'Edit', edit_listing_path(listing) , class: "btn btn-link" %>
                        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %>
                     <% end %>
                     
                   </div>         
                 </div>
               </div>
             <% end %>
     
       </div>
  
</div>


<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-12">
     <%= paginate @listings, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm' %>   
  </div>  
</div>

app/views/listings/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 offset-md-1 sm-12">
        <h1>New Listing</h1>
           <%= render 'form' %>
           <%= link_to 'Back', listings_path, class: "btn btn-link"  %>	
    	
    </div>  	
  </div>
 
</div>

app/views/listings/seller.html.erb
<div class="container">
  <h2 class="center big-title">Your Listings</h2> 

   <table class="table table-striped table-bordered">
  <tr>
    <th class="center seller-heading">Image</th>
    <th class="center seller-heading">Name</th>
    <th class="center seller-heading">Description</th>
    <th class="center seller-heading">Price</th>
    <th class="center seller-heading">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td class="seller-row"><%= image_tag listing.image.url(:thumb) %></td>
      <td class="seller-row"><%= listing.name %></td>
      <td class="seller-row"><%= listing.description %></td>
      <td class="seller-row"><%= number_to_currency(listing.price) %></td>
      <td class="valign">
         <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Action<span class="caret"></span>            
          </button> 
           <ul class="dropdown-menu" role="menu">
             <li><%= link_to "View", listing, class: "btn btn-link" %></li>
             <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li> 
             <li> <%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li> 

           </ul>
             
           </div>
     

      </td>
    </tr>
  <% end %>
</table>
   

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>
  
</div>

app/views/listings/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <%= image_tag @listing.image.url %>
        </div>
      </div>
      <div class="col-md-6">
        <h3><%= @listing.name %></h3>
        <p><%= number_to_currency(@listing.price) %></p>
        <p><%= @listing.description %></p>
        <%= link_to "Buy It Now!", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
      </div>
    </div>
              <% if (user_signed_in?) && (current_user == @listing.user) %>     
    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %>
    <%= link_to 'Back', listings_path, class: "btn btn-link" %>
    <% end %>
  
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="center">
  
  <%= link_to 'New Order', new_listing_order_path(@listing), class: "btn btn-primary" %>
  
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Purchase History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.seller.name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/orders/sales.html.erb
<div class="container ">
  <div class="center">
  <h2 class="big-title">Your Sales History</h2> 
</div>

<table class="table table-centered table-bordered">
  <tr>
    <th class="center row-heading">Image</th>
    <th class="center row-heading">Item</th>
    <th class="center row-heading">Price</th>
    <th class="center row-heading">Customer</th>
    <th class="center row-heading">Date Sold</th>

    
  </tr>

  
  <% @orders.each do |order| %>
    <tr class="row-parent">
      <td class="center row-text" style="vertical-align: middle;"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center row-text"><%= order.listing.name %></td>
      <td class="center row-text"><%= number_to_currency(order.listing.price) %></td>
      <td class="center row-text"><%= order.buyer.name %></td>
      <td class="center row-text"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>
  
</table>
  
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/home.html.erb
<div class="jumbotron">
    <%= form_tag search_path, class: "navbar-form ", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "What are you shopping for?", class: "form-control", id: "search-form" %>
           <%= submit_tag "Search", class: "btn", id: "search-button" %>
        </div>
      <% end %>
  
</div>

<div class="text-center container">
  <h1 id="main-heading">Buy or sell anything</h1>
   <h2>Search by Category</h2>
</div>
<div class="row text-center">
  <div class="col-md-10 col-md-offset-1 col-sm-12">
    <div class="col-md-2">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <img src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/rolex.jpg">          
      </div>
      <div class="panel-body">
        <p id="panel-text">Jewelry</p>
      </div>
      
    </div>  
  </div>
   <div class="col-md-2">

     <div class="panel panel-default">
      <div class="panel-heading preview">
         <%= link_to listings_path do %>
         <img src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/clothes.jpg"> 
      <% end %>

      </div>
      <div class="panel-body">
        <p id="panel-text">Clothing</p>
      </div>
      
    </div>  



    
  </div>
   <div class="col-md-2">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <img src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/curtains.jpg">          
      </div>
      <div class="panel-body">
        <p id="panel-text">Home & Living</p>
      </div>
      
    </div>  
  </div>
   <div class="col-md-2">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <img src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/toys.jpg">          
      </div>
      <div class="panel-body">
        <p id="panel-text">Toys & Games</p>
      </div>
      
    </div>  
  </div>
   <div class="col-md-2">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <img src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/computer.jpg">          
      </div>
      <div class="panel-body">
        <p id="panel-text">Electronics</p>
      </div>
      
    </div>  
  </div>
  </div>


  
</div>
<div class="orange-sec text-center">
  <h1 class="orange-text space" id="yellow-pad">Start selling today</h1>
  <h3 class="lower-text">Join millions of people who list their products at Etsy</h3>
</div>

<div class="text-center">
   <h2 id="text-pad">Editor's Pick</h2>

</div>

<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="collection-box" >
      <img class="collection-image" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/school.jpg"> 
      <span class="text-center collection-text valign">Back to school trends</span>  
    </div>
    
  </div>
   <div class="col-md-6 col-sm-12">
    <div class="collection-box" >
      <img class="collection-image" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/dress4.jpg"> 
      <span class="text-center collection-text valign">Summer Collection</span>  
    </div>
    
  </div>

  
</div>

<div class="text-center">
   <h2 id="text-review">Recent reviews from happy people.</h2>

</div>

<div class="row">
  <div class="col-md-4 col-sm-12">
    <div class="panel panel default review-card">
      <div class="img-avatar">
        <img class="avatar" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/face1.jpg">
        
      </div>
      <div class="panel-body review-box center">
        <p>Emily <span class="quote">Wrote on August 12<span></p>
        <div class="stars">
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
        </div>
        <p>I loved really loved the dress!</p>
        <div class="image-box">
          <img class="img-box" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/dress3.jpg">
        
        </div>

      </div>
      
   
    </div>    
  </div>
    <div class="col-md-4 col-sm-12">
    <div class="panel panel default review-card">
      <div class="img-avatar">
        <img class="avatar" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/face5.jpg">
        
      </div>
    
        <div class="panel-body review-box center">
        <p>Emily <span class="quote">Wrote on July 20<span></p>
        <div class="stars">
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
        </div>
        <p>My mac was delivered on time</p>
        <div class="image-box">
          <img class="img-box" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/mac.jpg">
          
        </div>
      </div>

      
    </div>    
  </div>
  <div class="col-md-4 col-sm-12">
    <div class="panel panel default review-card">
      <div class="img-avatar">
        <img class="avatar" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/face3.jpg">
        
      </div>
    
       <div class="panel-body review-box center">
        <p>Emily <span class="quote">Wrote on June 15<span></p>
        <div class="stars">
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
          <span><img src="https://s3-us-west-2.amazonaws.com/yelp-demo/stars/star-on.png"></span>
        </div>
        <p>Loving my necklace. Will buy more!</p>
        <div class="image-box">
          <img class="img-box" src="https://s3-us-west-2.amazonaws.com/etsydemo5/main-page/necklace1.jpg">
          
        </div>
      </div>

      
    </div>    
  </div>  
</div>
<div class="text-center">
   <h2 id="text-pad">Browse from our latest collection.</h2>

</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <div class="row">
     <div class="col-md-10 col-md-offset-1">
         <div class="row">
           <% @listings.each do |listing| %>
               <div class="col-md-3">
                 <div class="panel panel-default">
                   <div class="panel-heading preview">
                   <%= link_to listing do %> 
                   <%= image_tag listing.image.url(:medium) %>
                   <% end %>
                   </div>
                   <div class="panel-body">
                     <h3 id="listing-name"><%= listing.name %></h3>
                  <span id="list-price"><%= link_to number_to_currency(listing.price), listing %></span>
                      <p id="seller-name"><%= link_to "Sold by #{listing.user.name}", listing %></p>
                
                     <% if (user_signed_in?) && (current_user == listing.user) %>                    
                        <%= link_to 'Edit', edit_listing_path(listing) , class: "btn btn-link" %>
                        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %>
                     <% end %>
                     
                   </div>         
                 </div>
               </div>
             <% end %>
     
       </div>
       
     </div>
     
   </div>
 
 

<br>

           <% if user_signed_in? %>

<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
  <% end %> 

app/views/pages/search.html.erb
<div class="container">
<div id="search-fm">
    <%= form_tag search_path, class: "navbar-form ", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "What are you shopping for?", class: "form-control", id: "form-search" %>
           <%= submit_tag "Search", class: "btn", id: "button-search" %>
        </div>
    <% end %>	
</div>
         <div class="row">
           <% @listings.each do |listing| %>
               <div class="col-md-3">
                 <div class="panel panel-default">
                   <div class="panel-heading preview">
                   <%= link_to listing do %> 
                   <%= image_tag listing.image.url(:medium) %>
                   <% end %>
                   </div>
                   <div class="panel-body">
                     <h3 id="listing-name"><%= listing.name %></h3>
                  <span id="list-price"><%= link_to number_to_currency(listing.price), listing %></span>
                   
                
                     <% if (user_signed_in?) && (current_user == listing.user) %>                    
                        <%= link_to 'Edit', edit_listing_path(listing) , class: "btn btn-link" %>
                        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %>
                     <% end %>
                     
                   </div>         
                 </div>
               </div>
             <% end %>
     
       </div>
	
</div>


<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-12">
     <%= paginate @listings, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm' %>  	
  </div>	
</div>